export const REGISTER_USER = "AUTH/REGISTER_USER";
export const REQUEST_REGISTER = "AUTH/REQUEST_REGISTER";
export const LOGIN_USER = "AUTH/LOGIN_USER";
export const REQUEST_LOGIN = "AUTH/REQUEST_LOGIN";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
