export const REGISTER_USER = "AUTH/REGISTER_USER";
export const REQUEST_REGISTER = "AUTH/REQUEST_REGISTER";
export const LOGIN_USER = "AUTH/LOGIN_USER";
export const REQUEST_LOGIN = "AUTH/REQUEST_LOGIN";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SAVE_MESSAGE = "MESSAGES/SAVE_MESSAGE";
export const GET_ALL_MESSAGES_FROM_CONVERSATION_REQUEST =
  "MESSAGES/GET_ALL_REQUEST";
export const GET_ALL_MESSAGES_FROM_CONVERSATION = "MESSAGES/GET_ALL";
export const GET_ALL_CONVERSATIONS_REQUEST = "CONVERSATIONS/GET_ALL_REQUEST";
export const GET_ALL_CONVERSATIONS = "CONVERSATIONS/GET_ALL";
